# Generated by Django 3.0.6 on 2020-05-11 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cowsay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('model_cow', models.CharField(choices=[('cow', 'Cow')], default='cow', max_length=5)),
            ],
        ),
    ]
